import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Icons } from "@/components/icons";
import { NavMenu } from "@/components/CustomComps/NavMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <NavMenu />
        {children}
        <div className="fixed bottom-4 right-4 flex items-center gap-2 text-indigo-600">
          <span className="text-sm font-semibold">Powered by</span>
          <Icons.bitbrains className="w-6 h-6" />
          <span className="text-sm font-bold">BitBrains</span>
        </div>
      </body>
    </html>
  );
}

// pages/map.tsx or app/map/page.tsx
// The MapPage component has been moved to its own file.

